#pragma once

#include "../Core.h"

namespace r8ge {
    class Event {
    public:
        enum class Type : unsigned char
        {
            NONE,

            // Generated by windows
#undef MOUSE_MOVED
            WINDOW_RESIZED, WINDOW_CLOSED, WINDOW_FOCUS, WINDOW_LOST_FOCUS,
            KEY_PRESSED, KEY_RELEASED,
            MOUSE_PRESSED, MOUSE_RELEASED, MOUSE_MOVED, MOUSE_SCROLLED,

            // Generated by the engine or by modules
            KILL_ENGINE
        };

        enum class Handler : unsigned char {
            NONE,
            ENGINE,
            USER
        };

    public:
        Event();
        virtual ~Event();

        // Type of the event, used to identify the event
        [[nodiscard]] Type getType() const;

        // Is the event handled? If so, it should be ignored by the dispatcher
        [[nodiscard]] bool isHandled() const;

        // Set the event as handled, so it will be ignored by the next call of the dispatcher
        void setToHandled();

        // Get the handler of the event, used to identify the handler
        [[nodiscard]] virtual Handler getHandler() const;

        [[nodiscard]] std::string to_string() const;
    protected:
        struct {
            Type type : 7;
            bool handled : 1;
        } m_header;
    };

    struct UserEvent : public Event {
        [[nodiscard]] Handler getHandler() const override;
    };
}
